#!/bin/sh
# Test for linux distributions.
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

if [ -e "`ls $dir/lib/ld-linux* 2>/dev/null`" ]; then
	if [ -e "$dir/etc/debian_version" ]; then
		short="Debian"
		long=$(printf "Debian GNU/Linux (%s)\n" "$(cat $dir/etc/debian_version)")
	# Mandrake may also have a redhat-release, so
	# check this first.
	elif [ -e "$dir/etc/mandrake-release" ]; then
		short="Mandrake"
		long=$(cat "$dir/etc/mandrake-release")
	elif [ -e "$dir/etc/redhat-release" ]; then
		short="RedHat"
		long=$(cat "$dir/etc/redhat-release")
	# Anything better than pkgtool?
	elif [ -e "$dir/sbin/pkgtool" ]; then
		short="Slackware"
		long="Slackware Linux"
	else
		short="Linux"
		long="unknown Linux distribution"
	fi
	
        label=$(count_next_label $short)
	result "$partition:$long:$label:linux"
	exit 0
else
	exit 1
fi
