#!/bin/sh
# Make sure filesystems are available.
set +e	# ignore errors from modprobe

FILESYSTEMS='ext2 ext3 reiserfs xfs jfs msdos vfat ntfs minix hfs hfsplus qnx4'

if [ ! -e /var/lib/os-prober/modules ]; then
	# Check for anna-install to make it easier to use os-prober outside
	# d-i.
	if type anna-install >/dev/null 2>&1; then
		for fs in $FILESYSTEMS; do
			ANNA_QUIET=1 DEBIAN_FRONTEND=none \
			log-output -t os-prober \
				anna-install "$fs-modules" || true
		done
		depmod -a >/dev/null 2>&1 || true
	fi

	for fs in $FILESYSTEMS; do
		modprobe $fs 2>/dev/null | logger -t os-prober
	done

	# We only want to keep this state inside d-i, so this is as good a
	# check as any.
	if type anna-install >/dev/null 2>&1; then
		touch /var/lib/os-prober/modules
	fi
fi
