#!/bin/sh
. /usr/share/os-prober/common.sh
set -e

partition="$1"
bootpart="$2"
mpoint="$3"
type="$4"

found_item=0

entry_result () {
	if [ -n "$kernel" ] && \
	   [ -e "$mpoint/$kernel" ]; then
		result "$rootpart:$bootpart:$title:$kernel:$initrd:$parameters"
		found_item=1
	fi
	kernel=""
	parameters=""
	initrd=""
	title=""
}

parse_grub_menu () {
	mpoint="$1"
	rootpart="$2"
	bootpart="$3"
	
	kernel=""
	parameters=""
	initrd=""
	title=""

	while read line; do
		debug "parsing: $line"
		set -- $line
		case "$1" in
			title)
				entry_result
				shift 1
				title="$(echo $@ | sed 's/://g')"
			;;
			kernel)
				# Hack alert: sed off any (hdn,n) but
				# assume the kernel is on the same
				# partition.
				kernel="$(echo $2 | sed 's/(.*)//')"
				shift 2
				parameters="$@"
				# Systems with a separate /boot will not have
				# the path to the kernel in menu.lst.
				if [ "$partition" != "$bootpart" ]; then
					kernel="/boot$kernel"
				fi
			;;
			initrd)
				initrd="$2"
				# Initrd same.
				if [ "$partition" != "$bootpart" ]; then
					initrd="/boot$initrd"
				fi
			;;
			boot)
				entry_result
			;;
		esac
	done

	entry_result
}

if [ -e "$mpoint/boot/grub/menu.lst" ]; then
	debug "parsing menu.lst"
	parse_grub_menu "$mpoint" "$partition" "$bootpart" < "$mpoint/boot/grub/menu.lst"
elif [ -e "$mpoint/boot/grub/grub.conf" ]; then
	debug "parsing grub.conf"
	parse_grub_menu "$mpoint" "$partition" "$bootpart" < "$mpoint/boot/grub/grub.conf"
fi

if [ "$found_item" = 0 ]; then
	exit 1
else
	exit 0
fi
