#!/bin/sh
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

if [ -x "$dir/servers/exec" ] && [ -e "$dir/hurd/init" ]; then
        label=$(count_next_label Hurd)
	echo "$partition:GNU/Hurd:$label:multiboot"
	exit 0
else
	exit 1
fi
