#!/bin/sh
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

if [ "$type" = minix ] && [ -f "$dir/minix" ]; then
	# XXX will chain loading work?
        label=$(count_next_label Minix)
	result "$partition:Minix:$label:chain"
	exit 0
else
	exit 1
fi
