#!/bin/sh

partition=$1
mpoint=$2
type=$3

debug() {
  logger -t microsoft-prober "debug: $@"
}

# Weed out stuff that doesn't apply to us
case "$type" in
  vfat) debug "$1 is a FAT32 partition" ;;
  msdos) debug "$1 is a FAT16 partition" ;;
  *) debug "$1 is not a FAT partition: exiting"; exit 1 ;;
esac

if [ -e "$2/kernel.sys" -a -e "$2/command.com" ]; then
  echo "$1:FreeDOS:FreeDOS:chain"
  exit 0
fi
