#!/bin/sh
# Probe for OS 9 via System suitcase check.
. /usr/share/os-prober/common.sh

set -e

partition="$1"
dir="$2"
fstype="$3"

case "$fstype" in
  hfs) debug "Partition is HFS" ;;
  hfsplus) debug "Partition is HFS+ (Mac OS 9 only, we hope)" ;;
esac

if [ -e "$dir/System Folder/System" ]; then
  label="$(count_next_label MacOS)"
  result "${partition}:Macintosh System 6/7, OS 8/9:${label}:macos"
  exit 0
else
  exit 1
fi
